/* AUTO-GENERATED FILE. DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * aapt tool from the resource data it found. It
 * should not be modified by hand.
 */

package net.mafro.android.wakeonlan;

public final class R {
  public static final class dimen {
    public static final int font_size=0x7f010000;
    public static final int list_item_height=0x7f010001;
  }
  public static final class drawable {
    public static final int btn_star_big_off=0x7f020000;
    public static final int btn_star_big_on=0x7f020001;
    public static final int ic_menu_info_details=0x7f020002;
    public static final int ic_menu_preferences=0x7f020003;
    public static final int ic_menu_sort_alphabetically=0x7f020004;
    public static final int ical=0x7f020005;
    public static final int icon=0x7f020006;
    public static final int wake=0x7f020007;
  }
  public static final class id {
    public static final int appwidget_button=0x7f030000;
    public static final int appwidget_text=0x7f030001;
    public static final int clear_wake=0x7f030002;
    public static final int history=0x7f030003;
    public static final int history_row_colon=0x7f030004;
    public static final int history_row_ip=0x7f030005;
    public static final int history_row_mac=0x7f030006;
    public static final int history_row_port=0x7f030007;
    public static final int history_row_star=0x7f030008;
    public static final int history_row_title=0x7f030009;
    public static final int historytitle=0x7f03000a;
    public static final int historyview=0x7f03000b;
    public static final int icon=0x7f03000c;
    public static final int ip=0x7f03000d;
    public static final int mac=0x7f03000e;
    public static final int menu_created=0x7f03000f;
    public static final int menu_delete=0x7f030010;
    public static final int menu_edit=0x7f030011;
    public static final int menu_lastused=0x7f030012;
    public static final int menu_sortby=0x7f030013;
    public static final int menu_sortby_group=0x7f030014;
    public static final int menu_usedcount=0x7f030015;
    public static final int menu_wake=0x7f030016;
    public static final int port=0x7f030017;
    public static final int send_wake=0x7f030018;
    public static final int tabhost=0x7f030019;
    public static final int title=0x7f03001a;
    public static final int waketitle=0x7f03001b;
    public static final int wakeview=0x7f03001c;
  }
  public static final class layout {
    public static final int history_list=0x7f040000;
    public static final int history_row=0x7f040001;
    public static final int main=0x7f040002;
    public static final int widget=0x7f040003;
    public static final int widget_configure=0x7f040004;
  }
  public static final class menu {
    public static final int history_menu=0x7f050000;
    public static final int main_menu=0x7f050001;
  }
  public static final class string {
    public static final int app_desc=0x7f060000;
    public static final int app_name=0x7f060001;
    public static final int button_cancel=0x7f060002;
    public static final int button_clear=0x7f060003;
    public static final int button_save=0x7f060004;
    public static final int button_wake=0x7f060005;
    public static final int invalid_mac=0x7f060006;
    public static final int ip=0x7f060007;
    public static final int mac=0x7f060008;
    public static final int menu_created=0x7f060009;
    public static final int menu_delete=0x7f06000a;
    public static final int menu_edit=0x7f06000b;
    public static final int menu_lastused=0x7f06000c;
    public static final int menu_sortby=0x7f06000d;
    public static final int menu_usedcount=0x7f06000e;
    public static final int menu_wake=0x7f06000f;
    public static final int packet_sent=0x7f060010;
    public static final int port=0x7f060011;
    public static final int send_failed=0x7f060012;
    public static final int tab_history=0x7f060013;
    public static final int tab_wake=0x7f060014;
    public static final int title=0x7f060015;
    public static final int title_history=0x7f060016;
    public static final int title_wake=0x7f060017;
  }
  public static final class style {
    public static final int tablet_title=0x7f070000;
  }
  public static final class xml {
    public static final int widget_info=0x7f080000;
  }
}